### ISSUE TITLE
calcBarcodeMultiplicities.pl error

### ISSUE THREAD

**Issue by arunprasanna83** [bcgsc/arks#12]
Hi,

I tried to run the following: '`calcBarcodeMultiplicities.pl barcoded.fastq.gz > read_multiplicities.csv`'. `barcoded.fastq.gz` is the file generated by `'longranger basic'`. I get bizzare error:```

sh: -c: line 0: syntax error near unexpected token `)'
sh: -c: line 0: `gunzip -c ?MPUk)?B????tŨ~??/?Y??$-u??8?????-đ??????(+???	???,qT?8-	?e?x9FIH?]??6,?"???7??nn)?vX??`???'
sh: -c: line 0: syntax error near unexpected token `$'\3109v\016\251\222\207''
U?? -c: line 0: `gunzip -c ?녃zZ??@Clz??o???&d?E;w?H??rg???z?A(?9v???	?Z
   ε?F8A??e?x?-&?|?????g??<??6d???
                                  ?Ұle??ކ?????p;^??9???\?L?`}2*Kq'
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
sh: -c: line 0: syntax error near unexpected token `newline'
sh: -c: line 0: `gunzip -c P?>'
sh: -c: line 0: syntax error near unexpected token `)'
sh: -c: line 0: `gunzip -c ?c?l?)??p-hY??EIl??X_?2?#?|? ?
                                                         06??yM???9?Х???I??5Eww??R??=??v?a?s?@?lE?`6?t??M?@?????=O~A??J?M?^2D#T̆?'R
                                   ?T???!N???|???[,f׫????vr??-??)??
                                                                   (V'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `gunzip -c (QN~??+??'ӆ?35?4??Ǿ.J???K[????#2??q???t???K??v.0??;f???Le??\0G/?tf?Wy??~ܐP?"e[??P5ю?%?ݏ??G???W.???????????6?Q??NPb?s?????=l??[>?cw(?"5?e???A?ʑ???ջ?,??nv?R?Ԅ?
?V??~?                  N?	???~cװ??Ճpx?$????:??!?b^?
```
Besides my folder gets filled up with too many unreadable files (~42k). Can you please let me know is it any bug ?

Thanks,
Arun

**Comment by lcoombe** [comment]
Hi Arun,
Here's the help page for ```calcBarcodeMultiplicities.pl```:
```
./calcBarcodeMultiplicities.pl 
Usage: ./calcBarcodeMultiplicities.pl <fof of gzipped fastq files>
```
The script is expecting a text file which lists all of the input gzipped fastq files - one per line. Make a text file which lists barcoded.fastq.gz, and specify that as input to the script.
```
echo barcoded.fastq.gz > reads.fof
./calcBarcodeMultiplicities.pl reads.fof > reads_multiplicities.csv
```

Here are the corresponding lines in ```arks-make``` that do this command:
```# Make fof file containing the reads filename
$(reads).fof: $(reads).fq.gz
        echo $^ > $@

# Create the barcode multiplicities file
$(reads)_multiplicities.csv: $(reads).fof
        $(bin)../bin/calcBarcodeMultiplicities.pl $^ > $@
```
Hope that helps!
Lauren

**Comment by arunprasanna83** [comment]
> Hi Arun,
> Here's the help page for `calcBarcodeMultiplicities.pl`:
> 
> ```
> ./calcBarcodeMultiplicities.pl 
> Usage: ./calcBarcodeMultiplicities.pl <fof of gzipped fastq files>
> ```
> 
> The script is expecting a text file which lists all of the input gzipped fastq files - one per line. Make a text file which lists barcoded.fastq.gz, and specify that as input to the script.
> 
> ```
> echo barcoded.fastq.gz > reads.fof
> ./calcBarcodeMultiplicities.pl reads.fof > reads_multiplicities.csv
> ```
> 
> Here are the corresponding lines in `arks-make` that do this command:
> 
> ```
> $(reads).fof: $(reads).fq.gz
>         echo $^ > $@
> 
> # Create the barcode multiplicities file
> $(reads)_multiplicities.csv: $(reads).fof
>         $(bin)../bin/calcBarcodeMultiplicities.pl $^ > $@
> ```
> 
> Hope that helps!
> Lauren

Thanks Lauren !. It worked.

Regards,
Arun

**Comment by lcoombe** [comment]
I'm glad you got it working!
