### ISSUE TITLE
arks on bioconda?

### ISSUE THREAD

**Issue by nick-youngblut** [bcgsc/arks#13]
It appears that ARKS is currently not available on bioconda. Are there any plans to add ARKS to bioconda any time in the near future? Bioinformatics software available from bioconda is generally much easier to install and maintain (eg., upgrade or install specific software versions), so it would be great to have ARKS on bioconda.

**Comment by lcoombe** [comment]
Hello @nick-youngblut ,
Thank you for your interest in ARKS! 
Adding ARKS to bioconda isn't a high priority for us right now, but I will definitely take note of your request. I totally agree that having ARKS on bioconda would make installation easier for our users.

**Comment by lcoombe** [comment]
Hi @nick-youngblut - Just a heads-up that though we haven't yet put ARKS on bioconda, we added the ARKS formula to homebrew/linuxbrew, so you can install it with: `brew install brewsci/bio/arks`
