### ISSUE TITLE
arks-make error : no rule to make target

### ISSUE THREAD

**Issue by lebarsarthur** [bcgsc/arks#15]
Hello arks team,

I am trying to run arks+LINKS on my draft assembly, but I get the following error when running the pipeline "$ arks-make arks reads=xxx draft=xxx":
```
make: *** No rule to make target `/xx/xx/xx/xx/GENOME_ASSEMBLY/10x/ARKS/data/SN_all_pseudohap_arks.fasta.fa', needed by `/xx/xx/xx/xx/GENOME_ASSEMBLY/10x/ARKS/data/SN_all_pseudohap_arks.fasta.renamed.fa'.  Stop.
```

This error isn't very clear to me: I ran longranger basic on my fastq files, and supernova run + mkoutput from this data to generate my scaffolds, with success. "arks/Examples/arks-make" and binaries are also in PATH.

This is on CentOS 7. Also prior to running arks I activate a conda environment holding LINKS, sparsehash and time binaries. This is not human data if that makes any difference.

Any idea about what do I do wrong ?

Thank you

**Comment by lcoombe** [comment]
Hi @Mada2,
It looks like you are providing absolute paths to your ```arks-make``` command? Try making soft links (```ln -s```) to the reads and assemblies file in your working directory prior to running the makefile.
Also, make sure that your command is in this form (If you draft assembly is ```assembly.fa```, and your post-longranger basic reads are ```lr.fq.gz```):
```
arks-make arks reads=lr draft=assembly
```
Hope that helps!
Lauren

**Comment by lebarsarthur** [comment]
I was indeed giving the full path to my files to the arks-make arks command (I was already using symlinks as arguments)...

The problem is now fixed, thank you @lcoombe !

**Comment by lcoombe** [comment]
Glad to hear you got it working!
