### ISSUE TITLE
Unable to get the correct output running the ARKS demo

### ISSUE THREAD

**Issue by lindseyperrin** [bcgsc/arks#19]
Hello, 

My lab-mates and I are trying to test our installation of ARKS on our Universities' Linux cluster using the runARKSdemo script supplied in the examples folder. (We actually had the department's IT specialist install it for us, so we're pretty sure it's set up correctly).  The problem we're having is that when we run the runARKSdemo script, it appears to run successfully and no errors are produced, however the output files created don't match the output supplied for comparison.  In the output file for the run, we see a repeated line "please check your multiplicity file", and the following:

Please check your multiplicity file.
Please check your multiplicity file.
Please check your multiplicity file.
Saw 1085 barcodes and keeping 0 read pairs out of 55288

What's stumping us is that the test_reads_multiplicites.csv file produced by our run matches the one in the output folder for comparison.  We're pretty confident that we have all the necessary software installed properly and ARKS, LINKS, and the arks-make file are all in our path when we execute the demo script.  We had our department's IT specialist run it also and he got the same result and was unsure why. 

Any advice or help you could give us would be very much appreciated!  We're hoping to be able to use ARKS on our own data in the future. 
Thanks so much for your time and effort!

**Comment by lindseyperrin** [comment]
We figured out the problem!  We think it was related to changes between 1.0.2 and 1.0.3.   If we change the default gap size back from 100 to 10 in makeTSVfile.py, then we reproduce the sample output.  Sorry to post unnecessarily!

**Comment by warrenlr** [comment]
This is valuable info to all users, thanks for reporting it here!

**Comment by lcoombe** [comment]
Thank you for the report @lindseyperrin, and I'm glad you got the test working properly. I have updated the test demo output files in bf0bc4e, so everything should be consistent now. The only differences between the previous test output files and the current ones are the gap lengths between the scaffolds (as you eluded to).
Ex:
v1.0.2
```
[lcoombe@lcoombe01 output]$ cat test_scaffolds_c5_m50-6000_k30_r0.05_e30000_z500_l5_a0.9.scaffolds
scaffold1,156162,f1z12455k15a0m10_f2Z72860k28a0m10_f3z70847
```
v1.0.3
```
[lcoombe@lcoombe01 output]$ cat test_scaffolds_c5_m50-6000_k30_r0.05_e30000_z500_l5_a0.9.scaffolds
scaffold1,156162,f1z12455k15a0m100_f2Z72860k28a0m100_f3z70847
```
