### ISSUE TITLE
Minimum coverage requirements for ARKS? 

### ISSUE THREAD

**Issue by lindseyperrin** [bcgsc/arks#20]
Hello, 
I was wondering what the minimum coverage for the 10X data is required to run ARKS.  When we align our 10X reads to our draft genome we get about 3X coverage and are were wondering if this is too low for ARKS for work with.  If we hope to use ARKS in the future, what sort of coverage should we aim for? 
Thank you for your help!

**Comment by lcoombe** [comment]
Hi @lindseyperrin ,

Yes, I think that 3X coverage is unfortunately a bit low. We haven't done any tests with coverage that low so I don't know exactly what the performance would be, but my intuition is that you will need more reads. We haven't done a comprehensive sweep of read coverages with ARKS, but for ARCS, we found that a minimum of ~20-25X coverage was needed to get decent results. In our group, we aim for ~40-50X at least for our genome assembly projects.

Hope that helps!
Lauren

**Comment by lindseyperrin** [comment]
That makes sense.  Thanks for your help!
