### ISSUE TITLE
Small ARKS bugs

### ISSUE THREAD

**Issue by lcoombe** [bcgsc/arks#3]
Hi Ben,

As I was doing the test runs for ARKS, I just noticed a few small bugs that I was wondering if you could look at?

1. With a large number of input read pairs, the number seems to overflow:
```
Processed 2130000000 read pairs.
Processed 2140000000 read pairs.
Processed -2140000000 read pairs.
Processed -2130000000 read pairs.
```
2. in the 'usage' text, it says that -e is 30000 by default, but I believe in the code it is actually set to 0. I think 30000 as default makes sense (and is what we said in the ARCS paper)

3. You mention that "Jaccard Index" is a misnomer for the mapping of barcodes to contig ends, but it's used to describe the corresponding "-j" parameter in the ARKS usage page -- would you be able to change that?

Thank you!

**Comment by jvhaarst** [comment]
The second options is fixed with 1b752be
