### ISSUE TITLE
Should I use ARC or ARK

### ISSUE THREAD

**Issue by tao-bioinfo** [bcgsc/arks#4]
I am totally confused with them, as the `pipeline_example.sh` in ARK is the same as that in ARC!!!

**Comment by warrenlr** [comment]
We will look into it.  In the meantime, you may wish to use ARKS on large genomes (2Gbp+) when scaffolding a very contiguous assembly (N50>500kbp).  If your baseline assembly is fragmented, I recommend using ARCS.  We are actively developing ARKS, so stay tuned.

**Comment by tao-bioinfo** [comment]
Thanks. If so, I think ARKS is more suitable
