### ISSUE TITLE
There is an arcs_test-demo for arks, but isn't an arks_test-demo needed for arks?

### ISSUE THREAD

**Issue by ckeeling** [bcgsc/arks#6]
I notice that the install test in Examples/arcs_test-demo is looking for arcs and not arks.  Is this correct?  If not, is it simply a matter of changing the "arcs" to "arks" where called?  Thanks!

**Comment by lcoombe** [comment]
Hello,
Thank you for pointing this out! I have updated the demo and the pipeline_example.sh script as well. We have a Makefile available which will run all the steps of ARKS for you (optionally running misassembly corrector Tigmint first), and I've made a note of that in the README.
Hope that helps!
Lauren

**Comment by ckeeling** [comment]
Perfect thanks, and confirmed success with my installation.
