### ISSUE TITLE
Question about interleaved input

### ISSUE THREAD

**Issue by marchoeppner** [bcgsc/arks#7]
Dear ARKS team,

looking forward to testing your tool, but got stuck right away with the required input format. 

Specifically, how are these interleaved files generated? Our Chromium output consists of a set of three fastq files (I, R1, R2), where the "I" file contains the map between barcode and read name. 

`Va354-7155_S1_L007_I1_001.fastq.gz  
Va354-7155_S1_L007_R1_001.fastq  
Va354-7155_S1_L007_R2_001.fastq`

Any advice would be welcome, thanks!
/Marc

**Comment by marchoeppner** [comment]
"head" for each file, to clarify:

**Va354-7155_S1_L007_I1_001.fastq.gz**:

> @ST-E00274:214:HHNJ2CCXY:7:1101:2666:1221 1:N:0:NAAACCCT
> NAAACCCT
> +
> #A-A-<A-
> @ST-E00274:214:HHNJ2CCXY:7:1101:3884:1221 1:N:0:NAAACCCT
> NAAACCCT
> +
> #--A-AF-
> @ST-E00274:214:HHNJ2CCXY:7:1101:4797:1221 1:N:0:NAAACCCT
> NAAACCCT

**Va354-7155_S1_L007_R1_001.fastq**

> @ST-E00274:214:HHNJ2CCXY:7:1101:2666:1221 1:N:0:NAAACCCT
> NGACTTTTCACAGACTCACGACTAATATTCAAAATAGACAAAGAACTCACATAAATCAATAGCATGGAAAAAAAACTGAATAAAAAATGGGCAGAATAAAGGAAAAAACAAATTTGCAAAGAAGACAAACAAAGGGCCAAAAGGTACATG
> +
> #AAAFAFFJJJJFJJ7AJFJFJFFFJ-FFA--FFJA-7F<---F7F7<7<<<7---7FA<<<AJ<<-AAFJ-F----7--7-A<JFFJ-AA-F7FF-7---7-7-A-7-A---77--7-A-7<--7F-A---7--<<-F7-AJ--7-7--
> @ST-E00274:214:HHNJ2CCXY:7:1101:3884:1221 1:N:0:NAAACCCT
> NTTACACTCTACTCATCATGCTGTAGATTCTTTACAGTCTAAGCCACCAAGAAATTACATACTGACAAACATTTAGTTTGCTTCCAGTTTTTATATATGAACATACACTAGTAAAACACATGGAAAAATCAAAACAATTATGAGAAGTTA
> +
> #AAFFJJJJJJFJJFJJJJFJFAFJJAFJJJ<FFJA<J--<FJJ-A-A<-<<<J-<<FJJJFFFFJFJJJJAAAJ<AFJ<JAFJJFAJAAJF<F--AF--FJJFF7A<7<--<FAFFJJJJAF<-AJFFJJJAFAJ<FFJ-<<-<-<7<F
> @ST-E00274:214:HHNJ2CCXY:7:1101:4797:1221 1:N:0:NAAACCCT
> NTGGGTCAGGAGTAGAGGGCTTTTGTAGGCTGTAGTCCATGCGGTCTCAAAGAGTTGGACATAACTGAGCATGCACACACTAGTAATACAGGTGTAAAAACTGAGGTGGTTGATAAATTACCACTAGACAAAGATACTGAAAGTATTGTA

**Va354-7155_S1_L007_R2_001.fastq:**

> @ST-E00274:214:HHNJ2CCXY:7:1101:2666:1221 2:N:0:NAAACCCT
> NGGGGTGCATATAACTTTGAAAATTAGTGCTTTTATTTTCTTTAGATAAAAATCCCAACAGATTTACTGTACTTTAAACTCTACTTTTATTGTTAATATTTTTGCGAAACCTCCCTGCTCTTTTCCATAGAACCTGCACCAATGTACAGT
> +
> #--<AAA-A<J---<J<JJ7F--<--FJJ-----7-<-----<F7--A<J------7<-7---<<---AAF7---7-7---<A--77<----77--7A-7F-77--7----7-)7FF)))7--7<7F-7<-7-<7-7)A7<F<--<<A-<
> @ST-E00274:214:HHNJ2CCXY:7:1101:3884:1221 2:N:0:NAAACCCT
> NTATGCTTTCATTGCCTTGGGCCCAGATTAATTCCTTGCTCAGGAACTCAGATCCTGCAAGCTGCATGGGATAGCCAGAAAAAAAAAAAAAAATTTTTTTTTAATAGCTATAACTTCTCATAATTGTCTTGATTTTTCCATGTTTTTTAC
> +
> #AAAFJFJJFJJJJJJJFJJJFJJFJJAJ-FJJA-FF---77-77A--7A--FJ-FF--F-F7A<F--F-7FF<F-<77AFJJFF<AAJ<-A--7FFFJJJF<<<7-77---7-7F--7--77-<<A-<77<F<JJJAA---AF-FAA77
> @ST-E00274:214:HHNJ2CCXY:7:1101:4797:1221 2:N:0:NAAACCCT
> NTTTGCACCCCCATGAACTGCCTGCCAGGCTCCTCCGTCCATGGGATTCTCCAGGCATGAATACTGGAGTGAGTTACCATGCCCTCCTTTAGGCTCTGTGTATACACATACATATACAACAGCTTAGAAAGTAAGTCTGGTCATTACTTT

**Comment by warrenlr** [comment]
Hello Marc,

Thank you for your message and interest in ARKS.
You first need to run 10x Genomics' Long Ranger BASIC on your data.  Running the Long Ranger pipeline is very important as it error-corrects barcodes using the white list.  ARC/KS will expect the barcode sequence in the fastq header BX tag, which will be added by Long Ranger. For more info, please consult :

https://support.10xgenomics.com/genome-exome/software/pipelines/latest/advanced/other-pipelines


We will make edits to the readme to clarify the process of preparing input data for ARC/KS.
Thank you,
Rene

**Comment by lcoombe** [comment]
Thanks for the comment, Marc -- I have updated the README to mention the requirement of running Long Ranger basic on the raw chromium reads prior to running the ARKS pipeline.

**Comment by ckeeling** [comment]
Hello Marc,

After running longranger basic, arks needs information on the barcodes:

```bash
~/bin/arks-master/bin/calcBarcodeMultiplicities.pl longranger.fof > multiplicity.info
```
(where longranger.fof is simply a file that lists the path to the output file from longranger, in my case labelled longranger.gz)
i.e.
```bash
cat longranger.fof 
longranger.gz
```

Then,
```bash
arks -p full -f scaffolds.fa -a multiplicity.info longranger.gz
```
(I believe this is all part of the arks-make script if you can use it)

**Comment by lcoombe** [comment]
Thanks @ckeeling for mentioning this detail! I have updated the README again to mention this file. That being said, the arks-make script will run all these steps for you which should make running the ARKS pipeline easier.

**Comment by lcoombe** [comment]
Closing this issue -- feel free to reopen if there are any more questions.
